# Generated by Django 5.0.1 on 2024-01-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('Repassword', models.CharField(max_length=30)),
                ('mobile', models.IntegerField(default=0)),
            ],
        ),
    ]
